# Introduction {#sec:introduction}

The summer (July-August) groundfish research vessel survey on the Scotian Shelf and in the Bay of Fundy was started in 1970 by Fisheries and Oceans Canada Maritimes Region. The survey was originally designed to measure the distribution and abundance of major commercial fish species. Over time, information on non-commercial species was also collected. The groundfish survey database storing the information collected during the annual survey provides the main source of fisheries-independent information for marine species in the region. This information is routinely used to support stock assessments, to produce species status reports and has been previously used to publish atlases of species distribution.

```{r nspecies, include=FALSE, cache=FALSE}
library(tidyverse)
```

The current document is an update of an earlier report [@Ricard:MARatlas:2013] that built on former atlases by updating a comprehensive suite of derived indices for `r nrow(read.csv("species-list-for-report-APHIA.csv", encoding = "UTF-8"))` species to assess population status and environmental preferences. The information collected during the survey is stored in a relational database management system archived at Fisheries and Oceans Canada Maritimes Region which contains detailed information about the sampling locations and the associated catch. Tow-level survey data is also publicly available from the Ocean Biogeographic Information System [@DFO:2016] and from the Open data portal supported by the federal government [@OpenData_MAR_RV]. The present atlas builds upon the work done by Fisheries and Oceans colleagues from the northern Gulf of St. Lawrence [@Bourdages:NGatlas:2012], southern Gulf of St. Lawrence [@Benoit:etal:2003:techreport] and on earlier work in the Scotian Shelf [@Simon:Comeau:1994; @Horsman:atlas:2009].

To facilitate updates and foster collaboration on the analyses of the survey data, the computer code necessary to extract the data, to perform the analyses presented herein, and to reproduce and update the current document is made available in a git repository [@Ricard-Gomez-2021]. 

The survey area covers three major Northwest Atlantic Fisheries Organization (NAFO) zones that divide the Scotian Shelf into the colder east 4V and 4W (strata 440-466) and warmer west 4X (strata 470-495). For each species, trends in geographic distribution and biomass or abundance are plotted. Some caution is required in interpreting the results obtained for several taxa due to low sample size as explained later in the text. The spatial extent of distribution is plotted over time to gauge how the area occupied has changed. The relationship between biomass and spatial extent reflects whether the species distribution expands when biomass increases. For each strata, the slope describing how local density varies with regional abundance was estimated [@Myers:Stokes:1989]. These slopes were then plotted against a habitat suitability index to identify important strata for each species. Then, length frequencies over time depicted any changes in mean size. The plots of condition over time revealed whether individual fish are fatter or thinner than their long term mean. Finally, depth, temperature and salinity preferences were estimated to gauge the range of environmental parameters [@Perry:Smith:1994:cjfas]. A full ecological interpretation of trends is beyond the scope of this report. Other documents stemming from peer-reviewed scientific processes under the auspices of the [Canadian Science Advisory Secretariat](https://www.dfo-mpo.gc.ca/csas-sccs/) (CSAS) provide further descriptions of spatio-temporal trends in different indicators and put the information collected during the summer groundfish research vessel survey in a more focused context (see for example @ClarkEmberley2011). 
