# Results

The plots generated for each species are presented in the Appendix.

## Description of Figures

### Type A
For Category L and S species: 

Spatial distribution of catch-per unit of effort, (CPUE, kilograms per tow) in July-August for the Bay of Fundy and Scotian Shelf in five-year periods. Spatial interpolation between tows was done using Inverse Distance Weight (IDW). The probability of occurrence (proportion of tows with catch records for a given species) was also reported for each five-year period.

For Category LR and SR:

Location of tows with catch over the period 1970-2012 (Type LR) or the period 1999-2012 (Type SR). Location of tows with catch over the period 1970-2012 (Type LR) or the period 1999-2012 (Type SR).

### Type B
For Category L, S and I species:

Stratified random estimate of CPUE (left panel), distribution indices (D75% and D95%, the minimum area containing 75% and 95% of biomass, middle panel), and distribution vs. weight per tow (right panel). The stratified random mean is plotted as a solid line with the 95% confidence region indicated by the solid grey line. The overall mean is plotted as a grey horizontal line and the overall mean plus or minus 50% of the standard deviation appear as horizontal dashed lines. In all three panels, the early years appear in blue and the last years appear in red. The predictions from a loess estimator are overlaid on the distribution indices (middle panel). The Pearson correlation coeffcient between D75% and biomass, and its statistical significance, are also reported in the right panel.

### Type C.
Length frequency distribution for NAFO divisions 4X and 4VW. A smoothed length frequency distribution is shown for each 7-year periods covered by the surveys.

### Type D.
Average fish condition for all fish lengths (black dots and black line), large fish (thick gray line), and small fish (thin gray line). Fish condition is presented for NAFO divisions 4VW (right panel) and 4X (left panel).

### Type E.
Cumulative frequency distributions of depth, temperature and salinity at all sampled locations (thick solid line) and at fishing locations with catch records (thin dashed line). The depth, temperature and salinity associated with 5%, 25%, 50%, 75% and 95% of the cumulative catch is shown in tabular fashion on the bottom right panel.

### Type F.
Slopes estimates from the density-dependent habitat selection model (y axis) plotted versus the median abundance during the top 25% of years. The red box indicates strata of particular importance for a species by identifying slopes that are within a standard error from zero and that are within the top 25% of median abundance. Each stratum is identified on the plot by the last two digits of its number.

## Summary of successful tows by year and stratum
There is something weird going on here, there are 2 tows with NAs for stratum, (HAM1980042 set 62 and HAM1982072 set 13).


<!-- Number of tows by stratum-year -->
```{r tabtowstratumyear1, results="asis"}
## set working directories
  main.path <- "../" ##here::here()
  
  report.path <- file.path(main.path, "Report-generation")
  
  figdata.path <- file.path(main.path, "Figures-data") ## where to store data for figures
  figcode.path <- file.path(main.path, "Figures-code") ## where to find code for figures
  fig.path <- file.path(main.path, "Figures-actual") ## where to store figures
  mapping.path <- file.path(main.path, "Mapping")## mapping folder for maps that won't change over time


tows.strata.year <- read.csv(file.path(report.path, "Atlas-summary-table-tows-by-year-stratum.csv"))

yrs <- 1970:1991
ii <- which(substring(names(tows.strata.year),3,6) %in% as.character(yrs))
tows.strata.year.1 <- tows.strata.year[,c(1,2,3,ii)]
nr <- nrow(tows.strata.year.1)
## blank the first two columns of the last row
tows.strata.year.1[49,1:2] <- ""

csas_table(tows.strata.year.1,
  col.names=c("Stratum","NAFO Div.","Area (km2)",as.character(yrs)),
  caption = paste0("Number of representative tows conducted in each stratum during the period ",yrs[1]," to ",yrs[length(yrs)]),
  format = "latex", align=c("c",rep("r",15))
  ) %>%
  kableExtra::landscape() %>%
#  kableExtra::kable_styling(font_size = 7, latex_options = "repeat_header", repeat_header_method = "replace") %>% 
  kableExtra::kable_styling(font_size = 6) %>% 
  sub("\\caption\\[\\]\\{\\}", "\\caption*{}", .) 

yrs <- 1992:2013
ii <- which(substring(names(tows.strata.year),3,6) %in% as.character(yrs))
tows.strata.year.2 <- tows.strata.year[,c(1,2,3,ii)]
nr <- nrow(tows.strata.year.2)
## blank the first two columns of the last row
tows.strata.year.2[49,1:2] <- ""

csas_table(tows.strata.year.2,
  col.names=c("Stratum","NAFO Div.","Area (km2)",as.character(yrs)),
  caption = paste0("Number of representative tows conducted in each stratum during the period ",yrs[1]," to ",yrs[length(yrs)]),
  format = "latex", align=c("c",rep("r",15))
  ) %>%
  kableExtra::landscape() %>%
#  kableExtra::kable_styling(font_size = 7, latex_options = "repeat_header", repeat_header_method = "replace") %>% 
  kableExtra::kable_styling(font_size = 6) %>% 
  sub("\\caption\\[\\]\\{\\}", "\\caption*{}", .) 

yrs <- 2014:2020
ii <- which(substring(names(tows.strata.year),3,6) %in% as.character(yrs))
tows.strata.year.3 <- tows.strata.year[,c(1,2,3,ii)]
nr <- nrow(tows.strata.year.3)
## blank the first two columns of the last row
tows.strata.year.3[49,1:2] <- ""

csas_table(tows.strata.year.3,
  col.names=c("Stratum","NAFO Div.","Area (km2)",as.character(yrs)),
  caption = paste0("Number of representative tows conducted in each stratum during the period ",yrs[1]," to ",yrs[length(yrs)]),
  format = "latex", align=c("c",rep("r",15))
  ) %>%
  kableExtra::landscape() %>%
#  kableExtra::kable_styling(font_size = 7, latex_options = "repeat_header", repeat_header_method = "replace") %>% 
  kableExtra::kable_styling(font_size = 6) %>% 
  sub("\\caption\\[\\]\\{\\}", "\\caption*{}", .) 

```

A total of `r tows.strata.year[nrow(tows.strata.year),ncol(tows.strata.year)]` representative tows were conducted for the period spanning from `r substring(names(tows.strata.year)[5],3,7)` to `r substring(names(tows.strata.year)[ncol(tows.strata.year)-1],3,7)`.
