# Discussion

This report builds on previous work and former atlases by updating a comprehensive suite of indices to give a snapshot of population status and environmental preferences of 104 fish and invertebrate species. The current document is not meant to replace stock assessments, species-specific analyses of abundance, biomass and distribution, or any targeted attempts to integrate information about species or group of species from the wide and disparate sources of data about marine organisms in the area covered by the DFO Maritimes summer trawl survey. It is rather meant to provide a reproducible set of tools to extract and visualize the information collected in the summer groundfish research vessel survey. It is hoped that this document can provide a stepping stone to conduct other ecological analyses using the trawl survey data and increase reproducibility and transparency of ecological information collected annually.

## Diversity of approaches used for mapping fish and invertebrates in the Scotian Shelf bioregion  

Different methods have been applied in the Northwest Atlantic, and specifically on the Scotian Shelf bioregion, to map fish and invertebrate species distribution. The present report, for example, builds upon the atlas of important habitat developed to map the persistence of relatively high biomass for key fish species using the summer groundfish research vessel survey [@Horsman:atlas:2009]. Important habitat was obtained by interpolating observed weight per each species using the IDW, and calculating areas with relatively persistent high biomass for periods representing different fishery management eras. To compliment information from this atlas, including additional representations of biomass and diversity, a similar IDW interpolation mapping procedure was followed by @Smith2015, @WardPaige2016, and @Bundyetal2017. The summer groundfish research vessel survey is typically conducted during the month of July. However, from the fall of 1978 through to the spring of 1985, DFO also conducted spring and fall surveys using the same sampling design. This unique seasonal data was used to map the seasonal spatial distribution of key demersal and other fish species using IDW interpolation on the Scotian Shelf from the spring, summer and fall between 1978 and 1985 [@Smith2015]. Following recommendations provided by @Kenchingtons2013, the spatial distribution of three indicators of biodiversity for fish and invertebrates were mapped using IDW interpolation to identify areas with persistently high values across fishery management eras, and compared with areas of persistently high abundance for selected species [@WardPaige2016]. This analysis revealed a lack of consistent relationships between areas of persist high diversity and persistent high biomass, suggesting that both can be used as independent and important spatial indicators of the system [@WardPaige2016]. Groupings of fishes and invertebrates based on size, habitat and feeding guild, were also mapped using IDW interpolations to identify hotspots of functional group diversity [@Bundyetal2017]. This analysis revealed a spatially and temporally variable distribution of functional diversity across the Scotian Shelf with notable areas of high and low diversity [@Bundyetal2017]. Top quintiles of each functional group using the IDW approach were used as representative layers for fish and invertebrates in the MPA Network design in the Scotian Shelf Bioregion (Serdynska et al. In press). IDW interpolation methods have also been used to map the distribution of individual species such as sea cucumbers (*Cucumaria frondosa*) in the Scotian Shelf bioregion [@Shackell2013], and sea scallop (*Placopecten magellanicus*) in Georges and Browns Bank [@Hubley2013]. 

Species Distribution Modelling (SDM), instead of IDW, can also be used to evaluate spatio-temporal dynamics by predicting and understanding past, present and future distribution of species using environmental predictors [@Robinson:2017]. A variety of modelling approaches are being implemented in Maritimes Region to map and predict fish and invertebrate species distribution by incorporating environmental predictors to account for seasonal and temporal variability. For example, a stock assessment of snow crab (*Chionoecetes opilio*) on the Scotian Shelf used data from the snow crab survey from 2005 to 2018 to map spatial data products for this stock, including annual predicted interpolations of potential habitat using Generalized Additive Models (GAM) and several environmental covariates including depth, curvature, slope, species composition, and annual temperature [@Zisserson2019]. Sea scallop predicted habitat using Maximum Entropy (MaxEnt) models were computed in the German Bank using data compiled via benthic habitat mapping and seafloor geotechnical surveys in 2006, 2009, and 2010 [@Brown:2012]. Predictions in the Scotian Shelf bioregion and the Northeast United States using datasets from DFO and the National Oceanic and Atmospheric Administration from 1993 to 2012 also predicted sea scallop habitat at a wider scale based on three scenarios of seasonal temperature and salinity climatologies (NOAA) [@Lowen:2019]. Offshore American lobster stock assessments (*Homarus americanus*) used data from the RV, DFO Georges Bank, and National Marine Fisheries Service (NMFS) Northeast Fisheries Science Center (NEFSC) bottom trawl surveys (1970 to 2015) to predict species distribution using boosted regression trees and several environmental predictors (bathymetry, slope, curvature, and annual temperature interpolations) [@Cook:2017]. Information on the potential for recovery of cusk (*Brosme brosme*) used data from the bottom longline Halibut industry survey and Cusk absences in the Summer groundfish research vessel survey from 1998-2013 to predict suitable habitat using GAM, MaxEnt, and random forest models and several physical environmental variables (e.g. complexity, benthic current stress and complexity, temperature, salinity, primary production, chlorophyll, suspended matter) [@Harris:2018]. Atlantic halibut (*Hippoglossus hippoglossus*) assessments using Summer groundfish research vessel survey and NOAA survey data from 2001 to 2013 predicted juvenile habitat using MaxEnt model and environmental predictors (bathymetry, slope, bottom temperature) [@French:2018]. Persistent areas of high Atlantic halibut juvenile abundance were predicted using data from 27 bottom trawl surveys combined (NMFS and DFO) from 1978 to 2013 and applying Bayesian hierarchical spatiotemporal models with two environmental predictors (depth and temperature) [@Boudreau:2017]. 

These examples of mapping efforts in Maritimes Region showcase the diversity of approaches relevant to a variety of important research questions and management applications. Approaches, methods, datasets, and environmental predictors are selected based on individual project research questions, and considerations for each species, communities or stock. This allows research groups to maintain innovation and keep up with emerging methods and technologies to improve assessments, predictions, and ultimately, science advice. The diversity of approaches also leads to complexity when looking across studies as each data compilation and predictive method carries its own independent assumptions and can lead to different spatial outputs.

## Interpreting spatial results for marine spatial planning purposes   

Fisheries and Oceans Canada is leading a marine spatial planning process that brings together relevant authorities and stakeholders to better coordinate how we use and manage marine spaces to achieve ecological, economic and social objectives. Operationalizing marine spatial planning includes a series of steps, including the process of analyzing existing conditions by collecting and mapping information about ecological, environmental and oceanographic conditions [@Ehler:2009; @Agardy:2011]. Mapping the distribution of species is critical for the implementation of spatial management and as a first step in marine spatial planning processes. Species distribution have supported the identification of important sites for a given species or areas of high richness and diversity, which in turn can be used to inform siting decisions of new activities such as Marine Protected Areas (MPA), aquaculture sites or wind turbines. In the Scotian Shelf bioregion, mapping species distributions has been used to highlight areas of high biological diversity to support the identification of Ecologically or Biologically Significant Areas [@Ricard:MARatlas:2013; @WardPaige2016), to distinguish important and persistent habitat of significant species and functional groups to support MPA and conservation planning [@Horsman:atlas:2009; @Smith2015; @WardPaige2016; @Bundyetal2017], to identify important habitat for Species at Risk [@Harris:2018] and to highlight reserves for data-poor invertebrate fisheries [@Shackell2013]. Mapping species distribution has also been used to illustrate multi-decadal scale projections of changes in species distribution in the context of climate change and adaption [@Stanley:2018; @Greenan:2019]. 

In support of the marine spatial planning process, a public web-based atlas with relevant geospatial information is being developed to support decision-making. This Atlantic Canada-wide compilation of data and information will be a web-based, public platform with interactive maps of ocean ecosystems, human uses and management areas. This atlas cannot host the vast diversity of products and mapping approaches available in Maritimes Region. Consequently, we recommend that data products presented in this report should not be used for the atlas until an evaluation of the spatial information available and used in the past, is conducted. 

This diverse portfolio of approaches and applications is not unique to the Maritimes Region. A recent review of global distribution modelling efforts recommended the adoption of a consistent framework that integrates multi-model approaches and a clear expression of errors and uncertainties [@Robinson:2017]. In this context, Pacific Region has developed two initiatives to enable consistency and frequent publication, reproducibility, and transparency. One initiative developed a fully automated reproducible report to give a synthesis of data availability, population trends, fishing trends, growth and maturity patterns for 113 groundfish species in British Columbia to support stock assessment [@Anderson:2019]. The second initiative developed a SDM framework that was applied to twelve species on Canada’s Pacific coast as part of the Regional Response Plan [@Nephin:2019]. The Maritimes and Gulf region, through this and past reports, are also using similar reproducible approaches to facilitate annual updates and transparency [@Ricard-Gomez-2021; @Ricard:MARatlas:2013].
 
Recognizing the diversity of approaches for mapping fish and invertebrates in the Scotian Shelf bioregion, we recommend the development of a regional community of practice to compare and evaluate approaches for mapping, interpolating and/or modelling fish and invertebrates so future publications and advice related to spatial outputs can lead to more comparable work and consistent science advice to support processes such as marine spatial planning. At the international level, guidelines and standards related to appropriate variables and methods for mapping and modeling species and communities of deep-sea habitats were proposed to encourage the production of publications that will lead to more comparable work [@Kenchington2019]. Similar general guidance for group practice approach mapping would be a worthwhile product in Maritimes Region. Until then, we proposed the use of the Open Data record [@OpenData_MAR_RV] for the version 1.0 of the public web-based atlas.


# Acknowledgements  

We thank all the dedicated personnel involved in running trawl surveys in the Maritimes Region and the numerous colleagues in Maritimes Region that have shared information and advice in support of this report. The efforts of the Gulf Region secondary publications coordinators Alicia Cassidy and Jeff Clements in getting this report published are well appreciated.
