---
title: "Marine fish and invertebrate atlas: geographic distribution, population indices and environmental associations of marine species in the Scotian Shelf and Bay of Fundy derived from the annual Maritimes summer survey (1970-2020)"
year: 2022
report_number: nnn
author: |
  Daniel Ricard ^1^ 
  Catalina Gomez ^2^ 
  Jamie Emberley ^3^ 
  Catriona Regnier-McKellar ^3^ 
author_list: "Ricard, D., Gomez, C., Emberley, J. and Regnier-McKellar, C."
region: Maritimes Region
isbn: ""
address: |
  ^1^Science Branch\
     Gulf Region\
     Fisheries and Oceans Canada\
     Moncton, New Brunswick, E1C 5K4, Canada\
  ^2^Science Branch\
     Maritimes Region\
     Fisheries and Oceans Canada\
     Dartmouth, Nova Scotia, B2Y 4A2, Canada\
  ^3^Science Branch\
     Maritimes Region\
     Fisheries and Oceans Canada\
     St. Andrews, New Brunswick, E5B 0E4, Canada\
abstract: |
  The summer groundfish research vessel survey on the Scotian Shelf and in the Bay of Fundy started in 1970 and was designed to measure the distribution and abundance of major commercial fish species. Over time, additional information on non-commercial species was collected, and allowed considerable insight into ecosystem function and structure, as documented in many primary publications whose analyses used the survey data. The same groundfish survey database has also been used to produce species status reports, atlases of species distribution and remains an essential source of information for stock assessments in the Maritimes Region of Fisheries and Oceans Canada. This report builds on previous work and former atlases by updating a comprehensive suite of indices to assess population status and environmental associations of 103 species. For each species, trends in geographic distribution and biomass were plotted. The spatial extent of distribution was plotted over time to gauge how the area occupied has changed. The relationship between abundance or biomass and spatial extent reflected whether the species distribution expands when biomass increases. Length frequencies over time depicted any changes in mean size. The plots of condition over time revealed whether individual fish are fatter or thinner than their long term mean. Depth, temperature and salinity associations were estimated to gauge the range of suitable environmental parameters for each species. Finally, for each stratum, the slope describing how local density varies with regional abundance was estimated. The reproducible set of tools provided in this report constitutes a stepping stone to conduct other ecological analyses using the summer groundfish research vessel survey data by fostering reproducibility and transparency of ecological information collected and reported annually. Recognizing the diversity of approaches for visualizing and mapping fish and invertebrates in the Scotian Shelf bioregion, we recommend the development of a regional community of practice to compare and evaluate approaches for mapping, interpolating and/or modelling fish and invertebrates so future publications and advice can lead to more comparable work and consistent science advice to support processes such as marine spatial planning.
abstract_other: |
  Le relevé estival par navires de recherche sur le poisson de fond sur le plateau néo-écossais et dans la baie de Fundy a débuté en 1970 et visait à mesurer la répartition et l'abondance des principales espèces de poissons commerciales. Au fil du temps, des informations supplémentaires sur les espèces non commerciales ont été recueillies et ont permis de mieux comprendre la fonction et la structure de l'écosystème, comme le montrent de nombreuses publications primaires dont les analyses ont utilisé les données d'enquête. La même base de données sur les relevés du poisson de fond a également été utilisée pour produire des rapports sur la situation des espèces, des atlas de la répartition des espèces et demeure une source essentielle d'information pour les évaluations des stocks dans la région des Maritimes de Pêches et Océans Canada. Ce rapport s'appuie sur des travaux antérieurs et d'anciens atlas en mettant à jour une série complète d'indices pour évaluer l'état de la population et les associations environnementales de 103 espèces. Pour chaque espèce, les tendances de la répartition géographique et de la biomasse ont été tracées. L'étendue spatiale de la distribution a été tracée au fil du temps pour évaluer comment la zone occupée a changé. La relation entre l'abondance ou la biomasse et l'étendue spatiale indique si la répartition des espèces augmente lorsque la biomasse augmente. Les fréquences de longueur au fil du temps représentaient tout changement dans la taille moyenne. Les graphiques de l'état au fil du temps ont révélé si les poissons individuels sont plus gros ou plus minces que leur moyenne à long terme. Les associations en matière de profondeur, de température et de salinité ont été estimées pour évaluer la gamme de paramètres environnementaux appropriés pour chaque espèce. Enfin, pour chaque strate, la pente décrivant comment la densité locale varie avec l'abondance régionale a été estimée. L'ensemble d'outils reproductibles fournis dans ce rapport constitue un tremplin pour effectuer d'autres analyses écologiques à l'aide des données du relevé estival des navires de recherche sur les poissons de fond en favorisant la reproductibilité et la transparence de l'information écologique recueillie et rapportée annuellement. Reconnaissant la diversité des approches de visualisation et de cartographie des poissons et des invertébrés dans la biorégion du plateau néo-écossais, nous recommandons le développement d'une communauté de pratique régionale pour comparer et évaluer les approches de cartographie, d'interpolation et / ou de modélisation des poissons et des invertébrés afin conduire à des travaux plus comparables et à des avis scientifiques cohérents pour soutenir des processus tels que la planification de l'espace marin.
output:
 csasdown::techreport_pdf:
   french: false
   copy_sty: true
   line_nums: false
type:
  techreport
# ------------
# End of options to set
knit: bookdown::render_book
site: bookdown::bookdown_site
link-citations: true
bibliography: bib/refs.bib
csl: csl/csas.csl
lot: true
lof: true
# Any extra LaTeX code for the header:
header-includes:
 - \usepackage{multirow}
 - \usepackage{makeidx}
 - \makeindex
 - \usepackage{tocloft}
 - \cftsetindents{section}{1em}{1em}
 - \cftsetindents{subsection}{1em}{2.5em}

---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
options(xtable.comment = FALSE)
options(kableExtra.latex.load_packages = FALSE)
```

```{r load-libraries, cache=FALSE}
# `french` and `prepub` variables are extracted from the YAML headers above and
#  are used throughout the document. To make the document all in french, change
#  the line in the YAML header above to `french: true`
meta <- rmarkdown::metadata$output
if(length(grep("pdf", names(meta)))){
  french <- meta$`csasdown::techreport_pdf`$french
  prepub <- meta$`csasdown::techreport_pdf`$prepub
}else if(length(grep("word", names(meta)))){
  french <- meta$`csasdown::techreport_word`$french
  prepub <- meta$`csasdown::techreport_word`$prepub
}
if(french){
  options(OutDec =  ",")
}

# add other packages here:
library(dplyr)
library(ggplot2)
library(readr)
library(rosettafish)
library(tibble)
library(csasdown)

```
